package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
)

type resource struct {
	path, name string
}

func main() {
	resources := []resource{
		resource{
			path: "assets/animation/hero_animated.png",
			name: "Hero_animated_png",
		},
		resource{
			path: "assets/animation/hero.json",
			name: "Hero_json",
		},
		resource{
			path: "assets/animation/slash.png",
			name: "Slash_png",
		},
		resource{
			path: "assets/animation/slash.json",
			name: "Slash_json",
		},
		resource{
			path: "assets/tilesets/tiles.png",
			name: "Tiles_png",
		},
		resource{
			path: "assets/tilesets/tileset.tsx",
			name: "Tileset_tsx",
		},
		resource{
			path: "assets/tilesets/world-1.tmx",
			name: "World_1_tmx",
		},
	}

	f, err := os.Create("assets/assets.go")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	fmt.Fprintln(f, "// This file is generated by save_resources.go")
	fmt.Fprintln(f, "package assets")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "import \"log\"")
	fmt.Fprintln(f, "import \"io\"")
	fmt.Fprintln(f, "import \"os\"")
	fmt.Fprintln(f, "import \"bytes\"")
	fmt.Fprintln(f, "import \"fmt\"")
	fmt.Fprintln(f, "import \"github.com/pkg/errors\"")

	for _, r := range resources {
		content, err := ioutil.ReadFile(r.path)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Fprintf(f, "var %s    = []byte(%q)\n", r.name, string(content))
	}
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "var Lookup = map[string]([]byte){")
	for _, r := range resources {
		fmt.Fprintf(f, "%q:    %s,\n", r.path, r.name)
		absPath, err := filepath.Abs(r.path)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Fprintf(f, "%q:    %s,\n", absPath, r.name)
	}
	fmt.Fprintln(f, "}")
	fmt.Fprint(f, `
// Throws a log fatal if path doesn't exist
func LookupFatal(path string) []byte {
	fmt.Println("Read from disk", path, "'")
	if _, ok := Lookup[path]; !ok {
		log.Fatalf("no such resource %s", path)
	}
	return Lookup[path]
}

var ReadFromDisk bool

func FileReader(path string) (io.Reader, error) {
	if ReadFromDisk {
		f, err := os.Open(path)
		if err != nil {
			return nil, errors.Errorf("can't read file from disk: %s", err)
		}
		return f, nil
	}

	return bytes.NewReader(Lookup[path]), nil
}

func FileReaderFatal(path string) io.Reader {
	if ReadFromDisk {
		f, err := os.Open(path)
		if err != nil {
			log.Fatal("can't read file from disk", err)
		}
		return f
	}

	return bytes.NewReader(LookupFatal(path))
}
`)
}
